### ISSUE TITLE
[ERRO] Retira na Loja na Etapa de Identificação

### ISSUE THREAD

**Issue by raulvsjr** [elisei/checkout-identification-step#6]
Olá Elisei, tudo bem?

Tem duas alterações nesse modulo que gostaria de sugerir, uma é melhoria e a outra é solução de problema.

1 - Quando está inativo comprar em modo anonimo, não é possivel chegar até o checkout, ele pede a criação da conta/login antes.

Contornei isso permitindo compra anônima, mas removendo o botão continuar anônimo do Checkout.

2 - Retira na loja, está aparecendo na etapa de identificação, e de alguma forma está apresentando erro na finalização da compra.
Precisava fazer o retira na loja aparecer somente na etapa de entrega.

Eu estou um projeto a ponto de entrega, pendente somente a solução desse segundo problema.
Tem alguma alteração que você recomende pra resolver?

**Comment by elisei** [comment]
Olá @raulvsjr 

Obrigado pelo contato!

Sobre os pontos apontados:

1 - Esse comportamento está totalmente correto, não temos o porque atuar sobre ele. Senão deseja o método anonimo, ao desativar o usuário não chegará ao checkout sem estar logado. 

2 - Esse é o fluxo nativo da Magento, o retirar em loja não é um "meio de envio" pois de fato não há envio! :dancers:  e sim um comportamento totalmente diferente para a finalização do pedido.

**Comment by raulvsjr** [comment]
Então não há uma forma de inibir esse campos de retira na etapa de identificação e transferi-la para frete?

**Comment by elisei** [comment]
Olá @raulvsjr

Esse módulo é open-source e a plataforma também, então sim, você pode manipular qualquer um dos 2 livremente para melhor se adaptar ao seu conceito.

**Comment by elisei** [comment]
Issue fechado por falta de interação. Caso necessário, por favor reabra.
