### ISSUE TITLE
Bug ao digitar o email da etapa de identificação

### ISSUE THREAD

**Issue by https-pelaquin** [elisei/checkout-identification-step#8]
Olá bom dia, antes de qualquer coisa eu gostaria de dizer que gostei muito do seu módulo de full checkout.

**Resumo**
O módulo esta realizando a validação antes mesmo do usuário terminar de digitar o email.

**Descrição**
Ao realizar testes em uma loja com o modulo de Full Checkout eu percebi na etapa de identificação, especificamente no campo de email, o modulo esta realizando a validação antes do usuário terminar de digitar o email dele. Fiz o teste simulando uma pessoa que não tem prática de digitação e ao digitar por exemplo **teste@gmail.co** o modulo faz a validação do email, isto vale para hotmail e qualquer outro email. Se a pessoa digitar rápido este problema não acontece, mas caso ela digite devagar isso acaba atrapalhando a experiência do usuário pois muitas vezes ele nem irá perceber que não digitou o email completo.

**Sugestão**
Na etapa de identificação logo abaixo do campo email tem um botão "Próximo", pensei que seria interessante ocorrer a validação do email apenas se o usuário clicar nesse botão e não de forma automática como é hoje. CAMPO VAZIO = CONTINUA COMO ANÔNIMO, CAMPO PREENCHIDO = VALIDAÇÃO DO EMAIL.

**Comment by elisei** [comment]
Olá @https-pelaquin tudo joia?

Obrigado, fico feliz que tenha gostado! =]

Esse problema realmente ocorre mas não consigo pensar solução viável a todos os cenários. Explico;
- a consulta para o email digitado é essencial para que o cliente final veja ou o fomulário de cadastro ou o de login
- as ações (próximo, Continuar como Anônimo) são de prioridades mais baixas que os formulários citado.

Sendo assim, eu preciso que sempre que o usuário mude o email seja feita essa verificação (de qual formulário exibir) antes mesmo de qual botão o usuário irá ver.

Se ficar muito incomodado com esse comportamento, você pode fazer um mixin ou mesmo mover o js para sua pasta de tema e reescrever o delay desse fluxo aqui: 
https://github.com/elisei/checkout-identification-step/blob/Magento%402.4/view/frontend/web/js/view/form/step/identification.js#L79

Apenas uma observação, no futuro vou remover o input de email do formulário, criando um botão com "identificar-se com email e senha" para só então fazer a exibição do input e dele os forms. A intenção é "forçar" o usuário a utilizar sempre o login social e não mais "email e senha".

**Comment by https-pelaquin** [comment]
entendi a situação, nesse caso vou fazer o que você disse então. Gostei da ideia do login social, muita gente pede essa funcionalidade nas lojas.

Muito obrigado pela ajuda.
